/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Data.Structures2;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest{
    // Testing instantiate an empty linked list
    @Test public void testLinkedList(){

        System.out.println("sssssssss");
    }


    }
