/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Data.Structures2;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

// create an object of a linkedList
        Linkedlist linkedList = new Linkedlist();
//
        //Assign the head
        linkedList.head = new Node("a");
        Node second = new Node("b");
        Node third = new Node("c");

        //connecting the nodes
        linkedList.head.next = second;
        second.next = third;
        try {
            linkedList.insert("malek");
            System.out.println(linkedList.includes("a"));
            linkedList.insertBefore("c","Before c");
            linkedList.insertAfter("sd","After c");
            linkedList.append("last");
            System.out.println(linkedList.toString());


        }catch (Exception ex){
            System.out.println("error in: "+ ex);
        }

        //printing the node
//        System.out.print("LinkedList: ");
//        while (linkedList.head != null){
//            System.out.print(linkedList.head.value+" ");
//            linkedList.head = linkedList.head.next;
//        }

    }
}
