/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Data.Structures2;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {


        try {
            Linkedlist linkedList1 = new Linkedlist();
            Linkedlist linkedList2 = new Linkedlist();


            //Inserting Data for linkedList2
            linkedList2.insert(11);
            linkedList2.insert(22);
            linkedList2.insert(33);



        }catch (Exception ex){
            System.out.println("error in: "+ ex);
        }



    }
}
